version: '3'
services:   
    db:
        restart: always
        image: postgres
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        ports:
            - "5432:5432"
        volumes:
            - ./data/db:/var/lib/postgresql/data


    api: 
        build: 
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - ./api:/api
        ports:
            - 8000:8000 
        environment:
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on:
            - db
    
    
        
        